Repository platform9/express, pull requests merged in 2018-08, with the labels that each got.

#116 Fix issue #111
  pf9-express.yml
  roles/pre-flight-checks-openstack/tasks/main.yml
Labels: bug

#117 Fixes issue #107 and adds disable-swap role to K8s nodes
  pf9-express.yml
  roles/common/tasks/main.yml
  roles/common/tasks/ubuntu.yml
  roles/disable-swap/tasks/main.yml
Labels: enhancement

#126 added pip shade library to Ubuntu client pre-req
  pf9-express
Labels: bug

#120 Closes several logged issues to support promotion to master
  README.md
  group_vars/hypervisors.yml
  lib/config_util.sh
  lib/hosts.tpl
  lib/pf9-express.tpl
  myconfig.conf
  openstack-cli
  pf9-express
  pf9-express.yml
  roles/common/tasks/ubuntu.yml
  roles/map-role/tasks/main.yml
  roles/map-role/templates/pf9-ceilometer.j2
  roles/map-role/templates/pf9-neutron-dhcp-agent.j2
  roles/map-role/templates/pf9-neutron-ovs-agent.j2
  roles/map-role/templates/pf9-ostackhost-neutron.j2
  roles/neutron-prerequisites/tasks/main.yml
  roles/pre-flight-checks-openstack/tasks/main.yml
  scripts/k8s-tool
Labels: bug, enhancement

#137 Create License
  LICENSE
Labels: enhancement
